[package]
name = "redstone-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
quine-mc_cluskey = "0.2.4"
serde_json = "1.0.96"
structopt = "0.3.26"
sv-parser = "0.13.1"
